### PR TITLE
Gulp Refactor

### PR DESCRIPTION
**Pull request by jfmercer**
Gulp Refactor
--

This commit adds gulp to `angular-model` and also adds a significant
number of tasks.
  * Uses `run-sequence` to manage gulp tasks
  * Fixes coveralls support
    * Removes coveralls task from karma.conf.js
    * Adds coveralls task to gulp
  * Adds jscs task and .jscsrc
  * Adds jshint task and .jshintrc
  * Adds security audit task with `requireSafe`
  * Adds CodeClimate coverage and .codeclimate.yml
    * N.B. CodeClimate checks only `angular-model.js` and
      no other files.
  * Removes previous build script, which is now superfluous.

Additional changes
  * Changes style in the following:
    * `src/angular-model.js`
    * `spec/modelSpec.js`
    * `config/karma.conf.js`
    * `README.md`
  * `package.json` changes
    * Updates gulpfile packages to latest versions
    * Bumps version number to 0.5.0
    * Updates Nate's and Warren's contact info
    * Updates repository location
      * Changes uor to radify
    * Adds John as a contributor
      * This is necessary to allow John to publish `angular-model`
        to NPM
    * Adds keywords section
  * Moves `modelSpec.js` from `test/` to `spec/`
  * Deletes `coveralls.yml`, which is superfluous
  * Adds badges to README
    * Dependencies (david-dm.org)
    * CodeClimate score
  * Edits `CHANGELOG.md`

### CODE REVIEW

**Comment by nateabele** [comment]
This looks good. Why is it NOMERGE?

**Comment by jfmercer** [comment]
I'll still working on a few things.

1. I need to fix the sequence of the `gulp` tasks. Namely, `test` must _complete_ before `coveralls`.
1. AFAIK, it needs a `.jshintrc`, otherwise `jshint` does nothing. 
  * Side-note. Our OSS template lacks a standard `.jshintrc` file. I've [flagged this as an issue](https://github.com/radify/open-source-project-template/issues/12) and will take care of it myself. 
1. I want to get that damn `coverage` task/badge working. Not simply for this project, but so that I'll learn & know how to do so for other projects.
1. Nice-to-have: Replace the karma config with `gulp-jasmine` & `gulp-istanbul`. I got stuck on this point yesterday, but moved on. "If it ain't broke, don't fix it." 

Things not directly related to `gulp`:

1. The CHANGELOG must be updated.
1. The README needs some very slight additions. 
1. Pretty badges
  * Add `dependencies` and `devDependencies` badges
  * Possible a CodeClimate quality badge

A question for you: this project currently uses `angular-1.1.4` and `1.1.4`'s `mocks`. Should I experiment with updating that to Angular 1.2 or 1.3?

**Comment by nateabele** [comment]
> Should I experiment with updating that to Angular 1.2 or 1.3?

Yes, 1.3. Thanks.

**Comment by jfmercer** [comment]
@nateabele This is ready for review & merge. In addition to the description above, please note that neither the Coveralls nor the CodeClimate badge will work until merged into master. 

This repository needs more work, but I'll file those problems under Issues. 

Here are the reports:
  * [Coveralls](https://coveralls.io/github/radify/angular-model?branch=gulp-refactor)
  * [CodeClimate](https://codeclimate.com/github/radify/angular-model/compare/gulp-refactor)

**Pull request merged**
